import { useState } from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'

import Calendar from '../components/Calendar'
import Header from '../components/Header'
import { isEarlierDay, compareByDay, clampDay } from '../utils/date'
import { load } from '../utils/ical'
import type { Event, SerializedEvent } from '../utils/ical'

export const getStaticProps = async () => {
  const serializedEvents = await load('http://localhost:3000/basic.ics')
  return {
    props: {
      serializedEvents
    }
  }
}

const calculateSomeStateThings = (events: Event[], currentDay: Date) => {
  const sortedDates = events.flatMap(event => [event.start, event.end]).sort(compareByDay)
  const startingDay = sortedDates[0]
  const endingDay = sortedDates[sortedDates.length - 1]
  const initialDay = clampDay(startingDay, endingDay, currentDay)

  return {
    startingDay,
    endingDay,
    initialDay
  }
}

const Home: NextPage<{ serializedEvents: SerializedEvent[] }> = ({ serializedEvents }) => {
  const events = serializedEvents.map(event => ({
    ...event,
    start: new Date(event.start),
    end: new Date(event.end),
  }))

  const { startingDay, endingDay, initialDay } = calculateSomeStateThings(events, new Date('2022-10-16T00:00:00'))
  const [date, setDate] = useState(initialDay)

  const canPrev = isEarlierDay(startingDay, date) // startingDate < date
  const canNext = isEarlierDay(date, endingDay) // date < endingDate

  const prev = () => {
    const newDate = new Date(date)
    newDate.setDate(date.getDate() - 1)
    setDate(newDate)
  }

  const next = () => {
    const newDate = new Date(date)
    newDate.setDate(date.getDate() + 1)
    setDate(newDate)
  }

  return (
      <div className="w-full">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header date={date} onPrev={prev} onNext={next} canPrev={canPrev} canNext={canNext} />
        <Calendar events={events} date={date} />
      </div>
  )
}

export default Home
