name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"


      - name: Create temporary .env file
        run: |
          echo "ICAL_URL=https://raw.githubusercontent.com/JaninaWibker/fahrplan/main/public/example.ics" > .env

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
